context:
  version: "10.0.0"

package:
  name: pillow
  version: "{{ version }}"

source:
  - url: https://github.com/python-pillow/Pillow/archive/refs/tags/{{ version }}.tar.gz
    sha256: 535d17e830427bec163027114ded1def9ab0350c99bf1d8cb10535032967f3a5
    patches:
      - patches/setitup.patch
  - path: src/setup.cfg
  - path: setup.py

build:
  number: 0

requirements:
  build:
    - cross-python_emscripten-32
    - pip
  host:
    - python
    - zlib

extra:
  emscripten_tests:
    python:
      pytest_files:
        - test_import_Pillow.py
