context:
  version: "1.3.1"

package:
  name: joblib
  version: '{{ version }}'

source:
  - url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
    sha256: d0569f3b210583a17a66a06554d756dce4c23cde7fcbfcfcee93ccbf993217a7
    patches:
      - patches/0001-No-multiprocessing-1256.patch

build:
  number: 0
  script: python -m pip install . -vv

requirements:
  build:
    - cross-python_emscripten-32
    - python >=3.6
    - pip
  host:
    - python >=3.6
  run:
    - python >=3.6
    - setuptools

about:
  home: https://pypi.org/project/joblib/
  summary: 'Lightweight pipelining: using Python functions as pipeline jobs.'
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD

extra:
  emscripten_tests:
    python:
      pytest_files:
        - test_joblib.py
  recipe-maintainers:
    - martinRenou
