context:
  version: '2.0.3'

package:
  name: pandas
  version: '{{ version }}'

source:
  - url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
    sha256: c02f372a88e0d17f36d3093a644c73cfc1788e876a7c4bcb4020a77512e2043c
    patches:
      - patches/fix_json_signature.patch

build:
  number: 0

requirements:
  build:
    - cross-python_emscripten-32
    - numpy
    - cython
    - pip

  host:
    - python
    - numpy

  run:
    - numpy
    - python-dateutil
    - pytz


extra:
  emscripten_tests:
    python:
      pytest_files:
        - test_import_pandas.py
